/* Isolated synthetic browser QA. No application server, credentials or orders.
 * All browser HTTP and WebSocket traffic is intercepted; Edge background
 * networking is disabled, but this is not an OS egress-isolation certificate. */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../webapp/static'),out=path.resolve(process.argv[2]||'.phase0/terminal-visual');
const now=Date.now(),scope={tenant:'fixture',account:'0x'+'1'.repeat(40),network:'TESTNET'},instrument={network:'TESTNET',venue:'HYPERLIQUID',dex:'',symbol:'BTC'},leader='0x'+'2'.repeat(40);
const agentIds=['structure','momentum','volatility','liquidity','order_flow','leader','risk_context'];
const intent={intent_id:'fixture-open',scope,instrument,action:'OPEN',side:'BUY',size:.01,leverage:5,limit_price:60000,expires_ms:now+600000,slippage:{max_pct:.5}};
const fill={intent_id:intent.intent_id,instrument,order_id:'fixture-order',trade_id:'fixture-fill',side:'BUY',size:.01,price:60000,exchange_ms:now-3600000};
const action={intent_id:intent.intent_id,intent,origin:'AUTONOMOUS',status:'FILLED',receipt:{status:'FILLED',received_ms:now-3600000,order_ids:['fixture-order'],fills:[fill]},timestamp:now-3600000,correlation_id:'fixture-event'};
const agents=agentIds.map(id=>({agent_id:id,status:id==='order_flow'?'WAITING':'ACTIVE',result:{agent_id:id,instrument,created_ms:now,direction:id==='order_flow'?'WAIT':'LONG',confidence:.71,score:.6,evidence:['FIXTURE_EVIDENCE_ONLY'],invalidation:['PRICE_BREAK'],freshness:'FRESH',feature_version:'features-v1',strategy_version:'agents-v1'}}));
const consensus={created_ms:now,decision:'COPY_LONG',confidence:.74,participants:agentIds,blockers:[],supporting:['structure','momentum'],opposing:[],policy_id:'fixture-policy'};
const episode={episode_id:'fixture-episode',id:'fixture-episode',scope,mode:'PAPER_AUTO',origin:'AUTONOMOUS',leader,instrument,side:'LONG',state:'OPEN',entry:60000,current_price:60600,pnl:6,margin:120,notional:600,leverage:5,size:.01,created_ms:now-3600000,actions:[action],timeline:[{type:'LEADER_EVENT',timestamp:now-3605000,evidence:{action:'OPEN'}},{type:'ANALYSIS',timestamp:now-3604000,evidence:agents.map(a=>a.result)},{type:'CONSENSUS',timestamp:now-3603000,evidence:consensus},{type:'EXECUTION',timestamp:now-3600000,evidence:{status:'FILLED'}}]};
const closed=Array.from({length:12},(_,i)=>({...episode,episode_id:'closed-'+i,state:'CLOSED',outcome:{exit_ms:now-(12-i)*86400000,net_pnl:i%3===0?-3:7,return_pct:1},pnl:i%3===0?-3:7}));
const portfolio={completeness:'COMPLETE',equity:1200,available_collateral:800,positions:[{...episode,entry_price:60000,evidence:'VERIFIED',order_ids:['fixture-order'],origin:'MANUAL_LEADER_COPY'}]};
const runtime={mode:'PAPER_AUTO',runtime_mode:'PAPER_AUTO',portfolio,allocation:{allocation_limit:400,committed:120,reserved:20,available:260,status:'VERIFIED'},agents,consensus,episodes:[episode,...closed],actions:[action],analytics:{trade_count:12,sample_size:12,net_pnl:44,win_rate:8/12,profit_factor:4.66,expectancy:3.66,fees:2},calibration:[],execution:{unknown:0,partial:0,reconciliation_backlog:0}};
const leaderRow={wallet:leader,status:'ACTIVE',last_seen:now,analysis:{score:{score:.83,confidence:.71,profit_quality:.9,consistency:.8,drawdown_quality:.72,sample_quality:.91,recent_quality:.81,anomaly:.1,reasons:[]},windows:Object.fromEntries(['30','90','180'].map(k=>[k,{net_pnl:430,gross_profit:600,gross_loss:170,trades:60,profit_factor:3.5,win_rate:66.7,expectancy:7.1,avg_win:15,avg_loss:-8,best:40,worst:-20,max_drawdown:25,deep_analysis:{symbol_notional_share:{BTC:.6,ETH:.4},long_short_bias:{long:.7,short:.3},leverage_behavior:{value:null,reason:'LEVERAGE_NOT_PRESENT_IN_FILL_HISTORY'}}}]))}};
const snapshot={version:'product-v1',scope,checked_ms:now,live_auto:false,runtimes:[runtime,{...runtime,mode:'SHADOW',runtime_mode:'SHADOW',episodes:[]},{...runtime,mode:'LIVE_CONFIRM',runtime_mode:'LIVE_CONFIRM',episodes:[]}],account:{portfolio,actions:[{...action,origin:'MANUAL_LEADER_COPY'}]},manual_copy:{configured:true,enabled:true,status:'FOLLOWING',selected_leader:leader,allocation_pct:40,allocation_limit:480,committed:120,reserved:20,available:340,leader_capital_denominator:{'':12000,xyz:2400},denominator_evidence_type:'PER_DEX_MARGIN_SUMMARY_ACCOUNT_VALUE',last_leader_evidence_ms:now,positions:portfolio.positions},discovery:{status:'ACTIVE',counts:{OBSERVED:80,CANDIDATE:15,QUALIFIED:6,ACTIVE:3,PROBATION:1,RETIRED:2},leaders:[leaderRow],coverage:{observed_instruments:['BTC','ETH']},last_success_ms:now},health:{status:'DEGRADED',components:Object.fromEntries(['public_data','private_account','discovery','deep_analysis','watchlist','leader_detection','agents','consensus','authorization','allocation','risk','execution','reconciliation','events','database','telegram','web'].map(k=>[k,{status:k==='telegram'?'DEGRADED':'ACTIVE',last_success_ms:now}]))}};
const proposal={id:intent.intent_id,proposal_hash:'a'.repeat(64),intent,status:'PENDING',episode_id:episode.episode_id};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true,args:['--disable-background-networking','--disable-component-update','--no-first-run']});const report={widths:[],screens:[],errors:[],checks:0,fixture_only:true,exchange_orders:0};try{
for(const width of [375,390,430,1280,1440,1920]){const context=await browser.newContext({viewport:{width,height:920},serviceWorkers:'block'});await context.routeWebSocket('**/*',ws=>ws.close());let mutations=0;const commands=[];
await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!=='https://terminal-fixture.test')return route.abort();const p=u.pathname;if(p==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')});if(p.startsWith('/static/')){const name=path.basename(p);if(!['product.js','product-model.js','product.css'].includes(name))return route.abort();return route.fulfill({contentType:name.endsWith('.css')?'text/css':'text/javascript',body:fs.readFileSync(path.join(root,name),'utf8')});}
const json=body=>route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
if(p==='/api/product')return json(snapshot);
if(p==='/api/product/notification-preferences')return json({preferences:{OPEN:true,ADD:true,REDUCE:true,REVERSE:true,CLOSE:true,CRITICAL:true,LIVE_CONFIRM:true,...(route.request().method()==='PUT'?route.request().postDataJSON():{})}});
if(p==='/api/product/events/stream')return route.fulfill({contentType:'text/event-stream',body:'data: '+JSON.stringify({snapshot,events:[{id:'fixture-event',seq:1,type:'LEADER_EVENT',timestamp:now,data:{mode:'PAPER_AUTO'}}],cursor:1,reset_required:false})+'\n\n'});
if(p.startsWith('/api/product/positions/'))return json(episode);
if(p.startsWith('/api/product/leaders/'))return json(leaderRow);
if(p==='/api/product/confirmations/pending')return json({proposals:[proposal]});
if(p.endsWith('/approve')||p.endsWith('/reject')){mutations++;assert.deepEqual(route.request().postDataJSON(),{proposal_hash:proposal.proposal_hash});return json({...proposal,status:'REJECTED'});}
if(p==='/api/manual-copy'){mutations++;commands.push(route.request().postDataJSON());return json({configured:true});}
if(p==='/api/product/market/candles')return json({scope,coin:'BTC',mark:{price:60600,time:Date.now()},candles:Array.from({length:80},(_,i)=>({t:now-(80-i)*900000,o:59500+i*10,c:59510+i*10,h:59530+i*10,l:59480+i*10}))});throw new Error('Unexpected request '+p);});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.goto('https://terminal-fixture.test/');await page.waitForSelector('[data-key="hero"]');
const check=async name=>{await page.evaluate(()=>document.fonts.ready);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width} ${name} overflow`);await page.screenshot({path:path.join(out,`${width}-${name}.png`),fullPage:true});report.screens.push(`${width}-${name}`);report.checks++;};
await check('home');await page.locator('nav [data-nav="positions"]').click();await check('positions');await page.locator('[data-position]').first().click();await page.waitForSelector('#position-chart');await page.waitForTimeout(100);await check('position');
await page.locator('[data-nav="leaders"]').click();await check('leaders');await page.locator('[data-leader]').first().click();await check('leader');
await page.locator('[data-nav="agents"]').click();await check('agents');await page.locator('button[data-agent="momentum"]').click();await check('agent-detail');await page.locator('[data-close]').click();
for(const name of ['manual','analytics','health','settings']){await page.locator('[data-hub]').click();await page.locator(`dialog [data-nav="${name}"]`).click();await check(name);if(name==='manual'){await page.locator('[data-change-leader]').click();await page.locator('#allocation').fill('67');await page.locator('#manual-wallet').fill('0x'+'3'.repeat(40));await page.waitForTimeout(2200);assert.equal(await page.locator('#allocation').inputValue(),'67');assert.equal(await page.locator('#allocation-output').textContent(),'67');report.checks++;}}
await page.locator('[data-notification="OPEN"]').waitFor();await page.locator('[data-notification="OPEN"]').click();await page.waitForFunction(()=>document.querySelector('[data-notification="OPEN"]').getAttribute('aria-checked')==='false');report.checks++;
await page.locator('[data-hub]').click();await page.locator('dialog [data-nav="activity"]').click();await page.locator('[data-activity-filter="LEADERS"]').click();assert.equal(await page.locator('.activity-event').count(),1);await page.locator('.activity-event summary').click();assert.match(await page.locator('.activity-event pre').textContent(),/fixture-event/);await check('activity');report.checks+=2;await page.locator('[data-hub]').click();await page.locator('dialog [data-nav="settings"]').click();
await page.locator('[data-pending]').click();await page.locator('[data-proposal]').click();await check('confirmation');await page.locator('[data-reject]').click();await page.waitForSelector('dialog',{state:'detached'});assert.equal(mutations,1);report.checks++;
await page.locator('[data-hub]').click();await page.locator('dialog [data-nav="manual"]').click();assert.match(await page.locator('header .brand small').textContent(),/MANUAL COPY/);if(!await page.locator('#manual-wallet').isVisible())await page.locator('[data-change-leader]').click();await page.locator('#manual-wallet').fill('0x'+'3'.repeat(40));await page.locator('#allocation').fill('67');await page.locator('#manual-form button[type="submit"]').click();await page.locator('[data-manual-action="start"]').click();await page.waitForSelector('dialog',{state:'detached'});assert.deepEqual(commands.at(-1),{leader:'0x'+'3'.repeat(40),allocation_pct:67,action:'start'});await page.locator('#manual-wallet').fill('0x'+'4'.repeat(40));await page.locator('[data-stop]').click();await page.locator('[data-manual-action="stop"]').click();await page.waitForSelector('dialog',{state:'detached'});assert.deepEqual(commands.at(-1),{leader,allocation_pct:40,action:'stop'});assert.equal(mutations,3);report.checks+=3;
await page.locator('[data-nav="home"]').click();const retained=await page.evaluate(()=>{window.savedCanvas=document.querySelector('canvas');window.savedRoot=document.querySelector('[data-key="hero"]');return true;});await page.waitForTimeout(2300);assert.equal(await page.evaluate(()=>savedCanvas===document.querySelector('canvas')&&savedRoot===document.querySelector('[data-key="hero"]')),true);report.checks++;
const savedManual=snapshot.manual_copy;snapshot.manual_copy={...savedManual,enabled:false,paused:true,status:'PAUSED',ui_state:'PAUSED',capital_status:'FRESH',allocatable_capital:1200,valid_actions:['RESUME','CHANGE_LEADER']};runtime.session={session_id:'fixture-paper-session',start_ms:now-3600000,evaluation_end_ms:now+14*86400000,virtual_starting_capital:100,allowed_instrument:'BTC'};runtime.allowed_instrument=instrument;await page.reload();await page.waitForSelector('[data-key="hero"]');await page.locator('[data-hub]').click();await page.locator('dialog [data-nav="manual"]').click();assert.equal(await page.locator('#manual-wallet').isVisible(),false);assert.match(await page.locator('#manual-form button[type="submit"]').textContent(),/ВОЗОБНОВИТЬ/);assert.doesNotMatch(await page.locator('#manual-form button[type="submit"]').textContent(),/НАЧАТЬ/);await check('manual-paused');await page.locator('[data-change-leader]').click();assert.equal(await page.locator('#manual-wallet').isVisible(),true);await page.locator('[data-nav="home"]').click();assert.match(await page.locator('[data-key="paper-session"]').textContent(),/fixture-paper-session/);await check('paper-session');report.checks+=4;snapshot.manual_copy=savedManual;delete runtime.session;delete runtime.allowed_instrument;
await page.locator('header [data-privacy]').click();assert.equal(await page.locator('body').evaluate(b=>b.classList.contains('privacy')),true);await page.locator('header [data-language]').click();assert.equal(await page.locator('html').getAttribute('lang'),'en');await check('home-en-private');assert.equal(mutations,3);report.checks++;report.widths.push(width);await context.close();}
assert.deepEqual(report.errors,[]);report.pass=true;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:true,widths:report.widths,checks:report.checks,screens:report.screens.length,errors:report.errors}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
