const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const M=require('../webapp/static/product-model.js');
const scope={tenant:'7',account:'synthetic-account',network:'TESTNET'};
const instrument={network:'TESTNET',venue:'HYPERLIQUID',dex:'',symbol:'BTC'};
const p={instrument,side:'LONG',order_ids:['order-1'],evidence:'VERIFIED',size:1};
const s={scope,account:{portfolio:{positions:[p]},actions:[{intent_id:'one',receipt:{order_ids:['order-1']}},{intent_id:'other',receipt:{order_ids:['other']}}]},runtimes:[{mode:'PAPER_AUTO',episodes:[{episode_id:'paper',state:'OPEN'}]},{mode:'SHADOW',episodes:[{episode_id:'shadow',state:'OPEN'}]}]};
test('null is not zero',()=>{for(const v of [null,undefined,'',false,'0',NaN,Infinity,-Infinity])assert.equal(M.number(v),null);assert.equal(M.number(0),0);});
test('no legacy paper substitution',()=>assert.deepEqual(M.positions({paper:{positions:[p]}},'PAPER_AUTO'),[]));
test('PAPER and SHADOW are separate',()=>{assert.equal(M.positions(s,'PAPER_AUTO')[0].id,'paper');assert.equal(M.positions(s,'SHADOW')[0].id,'shadow');});
test('live exact order linkage excludes same-instrument external action',()=>assert.deepEqual(M.positions(s,'LIVE')[0].actions.map(a=>a.intent_id),['one']));
test('live identity includes tenant',()=>assert.notEqual(M.liveId(scope,p),M.liveId({...scope,tenant:'8'},p)));
test('live identity includes network',()=>assert.notEqual(M.liveId(scope,p),M.liveId({...scope,network:'MAINNET'},p)));
test('live identity includes order proof',()=>assert.notEqual(M.liveId(scope,p),M.liveId(scope,{...p,order_ids:['other']})));
test('unresolved rejected episode remains visible',()=>assert.equal(M.isOpen({state:'REJECTED',unresolved:true}),true));
test('closed is not open',()=>assert.equal(M.isOpen({state:'CLOSED'}),false));
test('unexecuted proposal is not an open position',()=>{assert.equal(M.isOpen({state:'PROPOSED'}),false);assert.equal(M.isOpen({state:'RESERVED'}),false);});
test('timeline preserves exact correlation identity',()=>assert.deepEqual(M.timeline({timeline:[{timestamp:20,correlation_id:'b'},{timestamp:10,correlation_id:'a'}]}).map(t=>t.correlation_id),['a','b']));
test('curve excludes unknown outcome and future outcomes',()=>assert.deepEqual(M.curve({episodes:[{outcome:{exit_ms:5,net_pnl:2}},{outcome:{exit_ms:6,net_pnl:null}},{outcome:{exit_ms:20,net_pnl:99}}]},'ALL',10),[{time:5,value:2}]));
test('empty performance is empty not fake curve',()=>assert.deepEqual(M.curve(null,'ALL',20),[]));
test('stream deduplicates immutable identity',()=>assert.equal(M.mergeEvents([{id:'a',seq:1}],[{id:'a',seq:1}]).length,1));
test('retention reset clears old event view',()=>assert.deepEqual(M.mergeEvents([{id:'a',seq:1}],[{id:'b',seq:2}],true),[{id:'b',seq:2}]));
test('bounded event history',()=>assert.equal(M.mergeEvents([],Array.from({length:300},(_,i)=>({id:String(i+1),seq:i+1}))).length,200));
test('expired confirmation is disabled',()=>assert.equal(M.proposalValid({status:'PENDING',proposal_hash:'a'.repeat(64),intent:{expires_ms:9}},10),false));
test('exact immutable confirmation hash required',()=>assert.equal(M.proposalValid({status:'PENDING',proposal_hash:'latest',intent:{expires_ms:20}},10),false));
test('unknown execution cannot be confirmed as pending',()=>assert.equal(M.proposalValid({status:'UNKNOWN',proposal_hash:'a'.repeat(64),intent:{expires_ms:20}},10),false));
test('finite coherent candles only',()=>assert.equal(M.candles([{t:1,o:1,h:3,l:1,c:2},{t:2,o:NaN,h:3,l:1,c:2},{t:3,o:4,h:3,l:1,c:2}]).length,1));
test('markers require linked fill evidence',()=>assert.deepEqual(M.markers({actions:[{intent_id:'a',intent:{action:'ADD'},receipt:{fills:[{exchange_ms:10,price:20,size:1}]}}]}),[{intent:'a',action:'ADD',time:10,price:20,size:1}]));
const base=path.resolve(__dirname,'../webapp/static'),html=fs.readFileSync(path.join(base,'index.html'),'utf8'),js=fs.readFileSync(path.join(base,'product.js'),'utf8'),css=fs.readFileSync(path.join(base,'product.css'),'utf8');
test('activity consensus is human-readable and retains technical IDs',()=>{const e=M.activityEvent({id:'audit',type:'CONSENSUS_UPDATED',data:{evidence:{event:{instrument:{symbol:'XLM'}},consensus:{decision:'WAIT',confidence:.63}}}});assert.equal(e.title,'AI_CONSENSUS');assert.equal(e.category,'AI');assert.equal(e.symbol,'XLM');assert.equal(e.action,'WAIT');assert.equal(e.confidence,.63);assert.equal(e.technical.event_id,'audit');});
test('activity classifies authoritative stream without discarding categories',()=>{for(const [kind,category] of Object.entries({POSITION_OPEN:'TRADING',AGENT_UPDATED:'AI',LEADER_EVENT:'LEADERS',RISK_UPDATED:'RISK',HEALTH_UPDATED:'SYSTEM'}))assert.equal(M.activityEvent({type:kind}).category,category);});
test('activity unknown confidence stays unavailable',()=>assert.equal(M.activityEvent({type:'CONSENSUS_UPDATED',data:{confidence:NaN}}).confidence,null));
test('activity raw details stay expandable and escaped',()=>{assert.match(js,/Технические детали/);assert.match(js,/esc\(JSON.stringify\(v.technical/);assert.match(css,/activity-arrival/);});
test('notification preferences use authenticated server storage',()=>{assert.match(js,/api\/product\/notification-preferences/);assert.match(js,/role="switch"/);assert.doesNotMatch(js,/pref\.set\([^\n]*notification/);});
test('activity includes risk filter and preserves node identities',()=>{assert.match(js,/\['ALL','TRADING','AI','LEADERS','RISK','SYSTEM'\]/);assert.match(js,/data-key="event-/);});
test('one primary runtime, no legacy owners',()=>{assert.doesNotMatch(html,/static\/(app|ai|chart|matrix|manual-trade|i18n)\.js/);assert.match(html,/product-model\.js/);});
test('product views never fetch legacy portfolio data',()=>assert.doesNotMatch(js,/\/api\/(dashboard|ai|intelligence|positions|report)[/'?"`]/));
test('no synthetic production signals or profit',()=>assert.doesNotMatch(js,/Math\.random|demoWallet|fakePnl/));
test('five primary navigation destinations',()=>assert.match(js,/\['home','positions','core','leaders','agents'\]/));
test('privacy persists and charts do not leak masked values',()=>{assert.match(js,/pref\.set\('wh_privacy'/);assert.match(css,/\.privacy \.financial-chart/);});
test('privacy covers analytics and wallet input',()=>{assert.match(css,/\.privacy #manual-wallet/);assert.match(css,/analytics-metrics/);});
test('initial mode is unknown and manual view never implies PAPER authorization',()=>{assert.match(js,/mode:'UNKNOWN'/);assert.match(js,/Manual Copy is independent/);});
test('unavailable position evidence does not display zero',()=>{assert.match(js,/num\(known\?open.length:null,0\)/);assert.match(js,/completeness==='COMPLETE'/);});
test('language preference persists',()=>{assert.match(js,/pref\.set\('wh_lang'/);assert.match(js,/document\.documentElement\.lang=S\.lang/);});
test('keyed updates preserve canvases and dirty inputs',()=>{assert.match(js,/o\.tagName==='CANVAS'\)continue/);assert.match(js,/S\.manualDirty/);assert.doesNotMatch(js,/terminal.*innerHTML\s*=/);});
test('stream resumes with authenticated fetch, bounded buffer',()=>{assert.match(js,/events\/stream\?after=\$\{S\.cursor\}/);assert.match(js,/buffer\.length>2000000/);assert.match(js,/x-telegram-init-data/);});
test('reduced motion and safe-area are supported',()=>{assert.match(css,/prefers-reduced-motion/);assert.match(css,/safe-area-inset-bottom/);});
